name: social_media_bdaya
description: a socialmedia project for bdaya development training
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  app_settings: ^5.1.1
  async: ^2.11.0
  bdaya_flutter_common: ^8.0.0
  bdaya_shared_value: ^3.1.3
  cross_file: ^0.3.4+1
  fixnum: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.7
  go_router: ^13.2.1
  grpc: ^3.2.4
  image_picker: ^1.1.2
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.3.5
  intl: any
  oidc: ^0.5.2
  oidc_default_store: ^0.2.0+8
  popover: ^0.3.0
  protobuf: ^3.1.0
  reactive_forms: ^17.0.1
  reactive_forms_annotations: ^5.0.0
  reactive_image_picker: ^5.0.1
  shared_preferences: ^2.2.2


dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  integration_test:
    sdk: flutter
  mason_cli: ^0.1.0-dev.53
  mocktail: ^1.0.0
  reactive_forms_generator: ^5.0.4
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
